?- vochong(tranminhtong, X).
?- vua(X).
?- me(X, cungtuc).
?- ongnoi(tranminhtong, trandutong).
?- me(huyninh, hoquily).
?- chigai(huyninh,trannghetong).
?- vochong(trandutong, thuctu).
?- congai(cungtuc, tranminhtong).
?- anhtrai(trandutong, tranhientong).
?- anhemho(tranthuantong, lethanhngau).
?- vochong(tranthuattong, lethanhngau).
?- ongnoi(tranminhtong, tranngac).
?- congchua(X, tranminhtong).
?- anhtrai(X, tranthuantong).
?- banoi(X, trannhuantong). 
?- ongbanoi(X, tranngac).
?- ongbangoai(X, giandinhde).		
?- ongngoai(X, hohanthuong).
?- bangoai(hientu, lethanhngau).
?- chu(trandutong, giandinhde).
?- bac(tranduetong, tranngac).
?- cau(trannghetong, tranphede).	
?- co(X, giandinhde).
?- hoangthaihau(X, trandutong).
?- hoanghau(huyninh, hoquily).
?- thaithuonghoang(X, trannghetong).
?- hoangde(X, trandutong).
?- hoangtu(tranngac, trannghetong).
?- hoangmuoi(X, tranhientong).
?- congchua(lethanhngau, trannghetong).
